### ISSUE TITLE
PDF is broken

### ISSUE THREAD

**Issue by fatih** [sarabander/sicp-pdf#13]
While trying to open it on Mac OSX Yosemite (latest version) I do get this:

![image](https://cloud.githubusercontent.com/assets/438920/8366076/67b58ebc-1b9a-11e5-8f69-8aa67a1bc9cd.png)

**Comment by sarabander** [comment]
I placed a quick link to [sicp.pdf](https://github.com/sarabander/sicp-pdf/raw/master/sicp.pdf) in the README. Cloned repo contains just a pointer to the file that is stored on the Github [LFS](https://github.com/blog/1986-announcing-git-large-file-storage-lfs) server. I enrolled in the early access program. External storage keeps the repo from growing by 7.2 MB each time I update the pdf.

**Comment by fatih** [comment]
Thanks for the clarification. It makes sense to add a link to Readme.

**Comment by fatih** [comment]
Thanks for the clarification. It makes sense to add a link to Readme.
