### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by ferronrsmith** [sarabander/sicp-pdf#15]
Seems to be a small spelling issue in the footnote of page 7

![2015-09-30-184849_3520x1080_scrot](https://cloud.githubusercontent.com/assets/159764/10208837/2c21786a-67a4-11e5-9cd3-4ae883675ea8.png)

**Comment by ferronrsmith** [comment]
never mind realized it was a continuation of the previous footnote

**Comment by sarabander** [comment]
Yeah, the footnotes tend to be rather long. Breaking them up is often unavoidable. This particular case is especially ugly because of the hyphenation. If I prevent the hyphenation, the line will be an underfull -- not pretty. So, compromises everywhere.
