### ISSUE TITLE
math italics for angel bracket notation?

### ISSUE THREAD

**Issue by dine2014** [sarabander/sicp-pdf#17]
In this book there are something that look like this:
< exp >

It seems that They are typeset as math formulas, for which TeX uses math italic. However, as the TeXbook points out, text italics should be used for identifiers more than one letter long. In this case I agree with Knuth, and the math italics makes the letters "e" "x" and "p" too apart and look like three individual letters, which is ugly.

Also, most of the codes in this books are Scheme codes, but some are English text. In this case, the typesetting program shouldn't highlight the keywords. It's strange to look at an English sentence which has most of the words in grey but an "and" bold and highlighted in blue.

**Comment by sarabander** [comment]
I'm delighted to encounter someone who pays such close attention to type aesthetics. I've been sloppy in typographic detail out of pure laziness and cluelessness. My graphic design education is ongoing and never-ending.

I've already made some commits, but wanted to experiment a bit more before I push the pdf. Thank you for pointing out the weak spots!

**Comment by dine2014** [comment]
There seems to be another glitch: near the beginning of 5.3.2 the word "useful" is spelt "use- ful". I don't know if this is already fixed though.

**Comment by sarabander** [comment]
No, you found this first and then I found some more. I put the hard hyphenations there myself back in 2011. Bad practice, but I really struggled with the hyphenation engine. At the time I compiled the PDF straight from Texinfo. Now it goes through LaTeX, and the hyphenation problems are somewhat relieved.

You've been super helpful! Thanks!

**Comment by sarabander** [comment]
The pdf is updated.
