### ISSUE TITLE
Would it be possible to also do the python version?

### ISSUE THREAD

**Issue by jiningq** [sarabander/sicp-pdf#18]
Hi,

First of all, thanks a lot for doing this. The pdf version is elegant and convenient and allows me to read the book even when I don't have internet access. Kudos to you guys.

I am just wondering whether it is possible for you to also do the later python version of SICP, available at the following link, in the reading column:

http://www-inst.eecs.berkeley.edu/~cs61a/fa11/61a-python/content/www/index.html#resources

I have no experience whatsoever with transforming an html format book into pdf so I can't even assess how much work this is. If it turns out to be really time consuming or something please just let me know.

Thanks!

**Comment by sarabander** [comment]
In fact, there are already pdf versions of chapters 1 and 2:
http://wla.berkeley.edu/~cs61a/fa11/lectures/functions.pdf
http://wla.berkeley.edu/~cs61a/fa11/lectures/objects.pdf
Maybe the author still has pdf-s of chapters 3 and 4 somewhere?

More recent installments of CS61A are based on John DeNero's http://composingprograms.com/. It is an excellent interactive book that lets you execute python code step-by-step and see the call stack and environment. The stepper works in offline mode, too. Also, there are videos embedded in the text. Converting the book to pdf would lose the dynamic features.

I feel that the pdf format is too inflexible for mobile reading. Although one can control typography and layout very precisely, it needs to be re-typeset for a range of screen sizes. It took several months to get the first pdf version to a decent shape. 

Have fun studying SICP!

**Comment by jiningq** [comment]
Thanks for the reply!

I see. I will take a look at the first two chapters and then the interactive site. Thanks again for putting together this book!
