### ISSUE TITLE
can't download pdf

### ISSUE THREAD

**Issue by dev4mobile** [sarabander/sicp-pdf#35]
this repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by plxty** [comment]
You can download the newer version by aswinmohanme, <https://github.com/aswinmohanme/sicp-pdf/blob/master/sicp.pdf>, or just build it yourself :)

**Comment by priyadarshan** [comment]
I am having issues even with [newer version](https://github.com/aswinmohanme/sicp-pdf/). One easy way is to fork the repository. Or build yourself, of course.

**Comment by dev4mobile** [comment]
@0b11111111  thanks
